<#
Run once per machine.

    bootstrap.ps1 [-Venv <existing venv root>] [-Force] [-Dev]

Writes machine.ps1 -- the only per-machine file, holding the only two
per-machine facts (the venv path and the CUDA verdict). Everything else the kit
needs is derived at runtime.

-Venv  reuse an existing venv instead of creating .venv beside this script.
-Force overwrite an existing machine.ps1.
-Dev   link the skills into ~\.claude\skills as a junction instead of copying,
       so edits flow both ways on the machine where they are authored.
#>
param([string]$Venv, [switch]$Force, [switch]$Dev)

$ErrorActionPreference = 'Stop'
$kit = $PSScriptRoot
$machineFile = Join-Path $kit 'machine.ps1'
if ((Test-Path -LiteralPath $machineFile) -and -not $Force) {
  throw "bootstrap.ps1: $machineFile already exists - pass -Force to overwrite"
}

# --- 1. venv ----------------------------------------------------------------
# A venv cannot be copied between machines: pyvenv.cfg and the console-script
# shims embed absolute interpreter paths. Reuse is a convenience, not the
# provisioning path.
if ($Venv) {
  $scripts = if (Test-Path -LiteralPath (Join-Path $Venv 'Scripts\python.exe')) { Join-Path $Venv 'Scripts' } else { $Venv }
  if (-not (Test-Path -LiteralPath (Join-Path $scripts 'python.exe'))) { throw "bootstrap.ps1: no python.exe under $Venv" }
  Write-Host "venv: reusing $scripts"
} else {
  $scripts = Join-Path $kit '.venv\Scripts'
  if (-not (Test-Path -LiteralPath (Join-Path $scripts 'python.exe'))) {
    # requirements.txt is a pip freeze from a 3.13 venv; on another minor version
    # wheels may be absent and the dependency set re-resolves -- which is exactly
    # what the version-fragile monkey-patches cannot absorb.
    $ver = (& python -c "import sys;print('%d.%d'%sys.version_info[:2])" 2>$null)
    if ($ver -ne '3.13') { throw "bootstrap.ps1: python on PATH is '$ver', need 3.13.x before creating the venv" }
    Write-Host "venv: creating $kit\.venv"
    & python -m venv (Join-Path $kit '.venv')
    $env:NO_PROXY = '*'   # this machine's system proxy is SOCKS-only; pip needs the bypass
    & (Join-Path $scripts 'python.exe') -m pip install --upgrade pip
    Write-Host "venv: installing torch (CUDA index) then requirements.txt"
    & (Join-Path $scripts 'python.exe') -m pip install torch==2.7.1+cu126 --index-url https://download.pytorch.org/whl/cu126
    & (Join-Path $scripts 'python.exe') -m pip install -r (Join-Path $kit 'requirements.txt')
  } else {
    Write-Host "venv: found $scripts"
  }
}
$python = Join-Path $scripts 'python.exe'
$pyver = & $python -c "import sys;print('%d.%d.%d'%sys.version_info[:3])"
if (-not $pyver.StartsWith('3.13.')) { throw "bootstrap.ps1: venv python is $pyver, requirements.txt is pinned against 3.13.x" }
Write-Host "venv python: $pyver"

# --- 2. CUDA verdict --------------------------------------------------------
# nvidia-smi on PATH is NOT the test: a driver present with a cpu-only torch in
# the venv would select cuda and crash at parse time.
$hasCuda = (& $python -c "import torch;print(torch.cuda.is_available())" 2>$null) -eq 'True'
Write-Host "cuda: torch.cuda.is_available() = $hasCuda -> MINERU_DEVICE_MODE will be $(if($hasCuda){'cuda'}else{'cpu'})"

# --- 3. machine.ps1 ---------------------------------------------------------
@"
# Generated by bootstrap.ps1 on $(Get-Date -Format 's') for $env:COMPUTERNAME.
# The only two per-machine facts. Gitignored on purpose. Re-run bootstrap -Force to regenerate.
`$VENV = '$scripts'
`$HasCUDA = `$$hasCuda
"@ | Set-Content -LiteralPath $machineFile -Encoding UTF8
Write-Host "wrote $machineFile"

# --- 4. skills --------------------------------------------------------------
# The kit repo is the source of truth; ~\.claude\skills is only an install
# target. A skill written only to the install target reaches machine 2 by no
# path at all.
$src = Join-Path $kit 'skills'
$dst = Join-Path $env:USERPROFILE '.claude\skills'
if (Test-Path -LiteralPath $src) {
  New-Item -ItemType Directory -Force -Path $dst | Out-Null
  foreach ($s in Get-ChildItem -LiteralPath $src -Directory) {
    $target = Join-Path $dst $s.Name
    if (Test-Path -LiteralPath $target) { Remove-Item -LiteralPath $target -Recurse -Force }  # overwrite, never merge into a stale folder
    if ($Dev) { New-Item -ItemType Junction -Path $target -Target $s.FullName | Out-Null }
    else { Copy-Item -LiteralPath $s.FullName -Destination $target -Recurse }
    Write-Host "skill: $($s.Name) -> $target$(if($Dev){' (junction)'})"
  }
} else {
  Write-Warning "no skills\ in the kit - nothing installed"
}

# --- 5. tiktoken seed -------------------------------------------------------
# A cold cache makes the first ingest download o200k_base from the Azure CDN,
# which times out on a SOCKS-proxied machine.
$seed = Join-Path $kit 'seed\data-gym-cache'
$cache = "$env:TEMP\data-gym-cache"
if (Test-Path -LiteralPath $seed) {
  New-Item -ItemType Directory -Force -Path $cache | Out-Null
  Copy-Item -LiteralPath $seed -Destination (Split-Path $cache -Parent) -Recurse -Force
  Write-Host "tiktoken: seeded $cache ($((Get-ChildItem $cache).Count) files)"
} else {
  Write-Warning "no seed\data-gym-cache in the kit - the first ingest will try to download o200k_base"
}

# --- 6. environment checks --------------------------------------------------
try { docker version --format '{{.Server.Version}}' | ForEach-Object { Write-Host "docker: server $_" } }
catch { Write-Warning "docker did not respond - start Docker Desktop before an ingest" }
foreach ($w in @("$env:WINDIR\Media\Ring10.wav", "$env:WINDIR\Media\Windows Critical Stop.wav")) {
  if (Test-Path -LiteralPath $w) { Write-Host "wav: $w" } else { Write-Warning "missing $w - notify.ps1 will fall back to beeps" }
}

Write-Host ""
Write-Host "Set RAGKIT_HOME, then RESTART every shell and every running Claude session before it takes effect:"
Write-Host "    [Environment]::SetEnvironmentVariable('RAGKIT_HOME', '$kit', 'User')"
